version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # --- OpenAI API Credentials ---
      # You can place your actual keys here for local development,
      # or use a .env file (see below).
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME:-qwen3-30b-a3b}

      # --- Redis Connection ---
      # This points to the 'redis' service defined below.
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    # To use a .env file, uncomment the line below
    # env_file:
    #   - .env

  redis:
    image: "redis:alpine"
    ports:
      # Expose redis to the host machine for debugging if needed
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: