version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # This points to the 'redis' service defined below.
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      # Expose redis to the host machine for debugging if needed
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: